### ISSUE TITLE
Archive page improvements

### ISSUE THREAD

**Issue by saxx** [technologieplauscherl/technologieplauscherl.github.io#40]
I have some suggestions for the single archive pages, for example http://technologieplauscherl.at/29/

- [x] Remove the Technologieplauscherl explanation text
- [x] Photos: Just put a link somewhere, instead of the headline and "findest du hier" sentence

What do you think?

**Comment by ddprrt** [comment]
I think doing some buttons (also with archive links to Meetup and Facebook) is the best idea here.
