### ISSUE TITLE
Text/images covered by menu

### ISSUE THREAD

**Issue by lischen3229** [technologieplauscherl/technologieplauscherl.github.io#52]
On the statistics and FAQ page, if the screen is too small or has a small resolution, the FAQ text and images are covered by the menu, see screenshot:
![screenshot](https://cloud.githubusercontent.com/assets/4456121/16835156/9c85d394-49b7-11e6-881f-d6322baf666b.png)

**Comment by ddprrt** [comment]
Füxed!
