### ISSUE TITLE
Google Map not working (Missing key)

### ISSUE THREAD

**Issue by saxx** [technologieplauscherl/technologieplauscherl.github.io#61]
On the plauscherl detail page at http://technologieplauscherl.github.io/42/ the map is not working. Problem, according to browser console, seems to be

    13:39:00.108 "Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error" 1 js:34:315
	_.jb https://maps.googleapis.com/maps/api/js:34:315
	Jm/this.f</< https://maps.googleapis.com/maps-api-v3/api/js/27/5/common.js:50:457
	_.yw</< https://maps.googleapis.com/maps-api-v3/api/js/27/5/common.js:202:171
	sm/c https://maps.googleapis.com/maps-api-v3/api/js/27/5/common.js:44:402
	<anonymous> https://maps.googleapis.com/maps/api/js/AuthenticationService.Authenticate:1:22

**Comment by DominikAngerer** [comment]
How to:
1) Create an API key as per instructions here: https://developers.google.com/maps/documentation/javascript/get-api-key

2) Edit the line in the plugin that loads the Google Maps API to include your key as the value of a ‘key’ parameter. Wherever you find “https://maps.googleapis.com/maps/api/js” or “http://maps.googleapis.com/maps/api/js” in the plugin, change it to “https://maps.googleapis.com/maps/api/js?key=YOUR_API_KEY”.

**Comment by saxx** [comment]
Thanks, @DominikAngerer for the detailed instructions 👍
