### ISSUE TITLE
Webseite ist kaputt

### ISSUE THREAD

**Issue by jakob** [technologieplauscherl/technologieplauscherl.github.io#88]
Hallo!

Bei mir geht die Plauscherl-Webseite grad nicht:

<img width="500" alt="screen shot 2017-04-05 at 20 40 23" src="https://cloud.githubusercontent.com/assets/198305/24721312/3b450186-1a40-11e7-8498-86ab93a19a87.png">

Ist da in den letzten Commits was schiefgegangen?

**Comment by hupfis** [comment]
On it...

**Comment by hupfis** [comment]
fixed
